version: '3'

services:
  database:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    ports:
      - "9200:9200"
    volumes:
      - ./tmp/elasticsearch:/usr/share/elasticsearch/data
      - ./config/containers/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml